######################################################################
#
# File name : tb_ip_1port_ram_compile.do
# Created on: Mon Sep 18 11:34:35 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.1c\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.1c\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.1c\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.1c\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.1c\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../ip_1port_ram.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_sim_netlist.v" \
"../../../../ip_1port_ram.gen/sources_1/ip/ila_0/ila_0_sim_netlist.v" \
"../../../../../rtl/ip_1port_ram.v" \
"../../../../../rtl/ram_rw.v" \
"../../../../../sim/tb/tb_ip_1port_ram.v" \


# compile glbl module
C:\\modeltech64_10.1c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

