######################################################################
#
# File name : tb_ip_1port_ram_wave.do
# Created on: Mon May 08 11:10:42 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
